# Generated by Django 5.0.6 on 2024-05-15 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReasoneComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_nr", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("ship_doc", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "tape_of_delivery",
                    models.CharField(
                        choices=[("P", "Pallet"), ("C", "Box")],
                        default="C",
                        max_length=1,
                        verbose_name="tape_of_delivery",
                    ),
                ),
                (
                    "reasone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zwroty.reasonecomment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr_order", models.CharField(max_length=20)),
                ("identifier", models.BigIntegerField(unique=True)),
                ("date_recive", models.DateTimeField()),
                ("comment", models.TextField()),
                ("transaction", models.TextField(blank=True)),
                ("complite_status", models.BooleanField(default=False)),
                (
                    "products",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zwroty.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zwroty.shop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkuInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_log", models.IntegerField()),
                ("sku_hand", models.IntegerField(default=0)),
                ("name_of_product", models.CharField(max_length=100)),
                ("barcodes", models.ManyToManyField(to="zwroty.barcode")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zwroty.skuinformation",
            ),
        ),
    ]
