# Generated by Django 4.1.13 on 2024-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skuinformation",
            name="sku_log",
            field=models.BigIntegerField(),
        ),
    ]
