# Generated by Django 5.0.6 on 2024-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnorder",
            name="position_nr",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="returnorder",
            name="date_recive",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
