# Generated by Django 5.0.6 on 2024-05-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0002_rename_sku_skuinformation_sku_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="skuinformation",
            name="sku_hand",
            field=models.IntegerField(default=0),
        ),
    ]
