# Generated by Django 5.0.6 on 2024-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0002_alter_skuinformation_sku_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tape_of_delivery",
            field=models.CharField(
                choices=[("op.", "Pallet"), ("pall.", "Box")],
                default="pall.",
                max_length=5,
                verbose_name="tape_of_delivery",
            ),
        ),
    ]
