# Generated by Django 5.0.6 on 2024-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0002_returnorder_position_nr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnorder",
            name="position_nr",
            field=models.IntegerField(),
        ),
    ]
