# Generated by Django 5.0.6 on 2024-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0003_alter_returnorder_position_nr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnorder",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
