# Generated by Django 5.0.6 on 2024-05-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0003_alter_product_tape_of_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnorder",
            name="products",
            field=models.ManyToManyField(blank=True, to="zwroty.product"),
        ),
    ]
