# Generated by Django 5.0.6 on 2024-05-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0004_alter_returnorder_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnorder",
            name="products",
        ),
        migrations.AddField(
            model_name="returnorder",
            name="products",
            field=models.ManyToManyField(to="zwroty.product"),
        ),
    ]
