# Generated by Django 5.0.6 on 2024-05-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0004_alter_returnorder_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnorder",
            name="generate_xls_status",
            field=models.BooleanField(default=False),
        ),
    ]
