# Generated by Django 5.0.6 on 2024-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0005_returnorder_generate_xls_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tape_of_delivery",
        ),
        migrations.AddField(
            model_name="returnorder",
            name="tape_of_delivery",
            field=models.CharField(
                choices=[("op.", "Paleta"), ("pall.", "Paczka")],
                default="pall.",
                max_length=5,
                verbose_name="tape_of_delivery",
            ),
        ),
    ]
