# Generated by Django 5.0.6 on 2024-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zwroty", "0006_remove_product_tape_of_delivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnorder",
            name="tape_of_delivery",
            field=models.CharField(
                choices=[("paleta", "Paleta"), ("paczka", "Paczka")],
                default="paczka",
                max_length=6,
                verbose_name="tape_of_delivery",
            ),
        ),
    ]
