# Generated by Django 5.0.6 on 2024-05-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("leader", "Leader"),
                    ("regular", "Regular User"),
                ],
                default="regular",
                max_length=10,
            ),
        ),
    ]
